dist: trusty

language: python
python: 3.6

matrix:
    include:
        - os: linux

addons:
  apt_packages:
    - pandoc

cache: pip

before_install:
  - sudo apt-get install python3-pip
  - sudo pip3 install requests

install:
  - pip install tornado==5.1.1
  - pip install lightkurve
  - pip install tensorflow
  - pip install astropy
  - pip install astroquery
  - pip install tqdm
  - pip install sphinx
  - pip install nbsphinx
  - pip install cython
  - pip install codecov
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install beautifulsoup4>=4.6.0
  - pip install lxml
  - pip install tess-point
  - pip install pybind11
  - python setup.py install

script:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-docs.sh; fi
  - pytest eleanor/tests/* --cov=eleanor/

after_success:
  - codecov
